// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaVQqhxrXFYrfMlF6MLvfQ2KNmbF47fGo',
    appId: '1:635486398019:web:29a1a93fbd4d384cd556f6',
    messagingSenderId: '635486398019',
    projectId: 'dicegame-22579',
    authDomain: 'dicegame-22579.firebaseapp.com',
    storageBucket: 'dicegame-22579.appspot.com',
    measurementId: 'G-C1L418G737',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLCquBBhp14eOekKL4sD1TRSb2H9fBLOA',
    appId: '1:635486398019:android:7c7a3cc4cd87e24bd556f6',
    messagingSenderId: '635486398019',
    projectId: 'dicegame-22579',
    storageBucket: 'dicegame-22579.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxQCs31CEa0oIUdAgkYPIhGuq1lr7-osw',
    appId: '1:635486398019:ios:4e828772e9867ccfd556f6',
    messagingSenderId: '635486398019',
    projectId: 'dicegame-22579',
    storageBucket: 'dicegame-22579.appspot.com',
    iosBundleId: 'com.example.diceGameCompanion',
  );
}
